### ISSUE TITLE
Cannot run setup:static-content:deploy

### ISSUE THREAD

**Issue by mmenozzi** [minimit/xtend-magento#1]
Steps to reproduce:
1. Follow the installation steps of the README on a clean version of Magento 2.2
2. Run `php bin/magento deploy:mode:set developer`
3. Run `php bin/magento setup:static-content:deploy -f`

Expected result: compilation should be successful.
Actual result:

```
ParseError: Unexpected input in _icon.less on line 46, column 6
44| // icon :before or :after
45|
46| .icon(@content, @size:@icon-medium, @sr-only:false, @position:before) {
47|   & when (@sr-only = true) {
48|     > span {
49|       .sr-only();
```

I think it's related to: https://github.com/oyejorge/less.php/issues/147

**Comment by minimit** [comment]
Fixed with 0.4.0 https://github.com/minimit/xtend-magento/releases/tag/v0.4.0
